stages:
  - test
  - deploy

test-job:
  stage: test
  script:
    - echo "Tests passed"
  only:
    - dev

deploy-job:
  stage: deploy
  script:
    - (docker ps -a --format {{.Names}} | grep social -w) && docker stop social && docker rm social || echo "Doesn't exist"
    - docker build -f /root/Dockerfile -t java-backend:1.0 .
    - docker run --name=social -d -p 8086:8086 -t java-backend:1.0
  only:
    - dev