stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - sudo mvn clean
    - sudo mvn package spring-boot:repackage

test-job:
  stage: test
  script:
    - echo "Tests passed"

deploy-job:
  stage: deploy
  script:
    - sudo docker stop vigilant_babbage
    - sudo docker build -t java-backend:1.0 .
    - sudo docker run -d -p 8086:8086 -t java-backend:1.0