stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - mvn clean
    - mvn package spring-boot:repackage

test-job:
  stage: test
  script:
    - echo "Tests passed"

deploy-job:
  stage: deploy
  script:
    - docker stop vigilant_babbage
    - docker build -t java-backend:1.0 .
    - docker run -d -p 8086:8086 -t java-backend:1.0