stages:
  - build
  - test
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

build-job:
  stage: build
  script:
    - mvn -f /root/javaproTeams30Backend/ clean
    - mvn -f /root/javaproTeams30Backend/ package spring-boot:repackage

test-job:
  stage: test
  script:
    - echo "Tests passed"

deploy-job:
  stage: deploy
  script:
    - (docker ps -a --format {{.Names}} | grep social -w) && docker stop social && docker rm social || echo "Doesn't exist"
    - docker build -t java-backend:1.0 .
    - docker run --name=social -d -p 8086:8086 -t java-backend:1.0