spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social
    username: postgres
    password: 123
  redis:
    host: localhost

auth:
  pass-restore: http://localhost:8080/change-password?token=
  email-restore: http://localhost:8080/shift-email?token=

