spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/network
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true




#applicationParams
socialNetwork:
  default:
    page: 0
    size: 20




