spring:
  jpa:
    hibernate:
    ddl-auto: validate
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://195.133.48.174:5432/social
    username: admin
    password: secret
    initialization-mode: never
    data: classpath:/db/changelog/data.sql
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
  mail:
      protocol: smtps
      host: smtp.mail.ru
      port: 465
      username: testbd@internet.ru
      password: hvYDUwgKj6fkDkFCkgSN
      properties.mail.smtp.auth: true
      properties.mail.smtp.ssl.enable: true
  redis:
    port: 6379
    host: localhost
  cache:
    type: redis
    redis:
      cache-null-values: true
    #redis: time-to-live: 40000
  main:
    allow-bean-definition-overriding: true


#applicationParams
socialNetwork:
  default:
    page: 0
    size: 20
    noteSize: 10
  timezone: Europe/Moscow

server:
  port: 8086

auth:
  secret: someSecretCode
  time-to-live: 3600000000
  pass-restore: http://195.133.48.174:8080/change-password?token=
  email-restore: http://195.133.48.174:8080/shift-email?token=

logging:
  file:
    max-history: 1
    path: log
    uploadLogs: true

yandex:
  OAuth: y0_AgAAAABmXrQEAAixEgAAAADUt4an1A5J737iQj-h8tddar39fPxBIgQ

user:
  time-to-delete: 2592000000
