server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost/postgres
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    data: classpath:/db/changelog/data.sql
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    properties:
      ssl.endpoint.identification.algorithm:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: soialNetworkApp.kafka.dto
  redis:
    port: 6379
    host: 127.0.0.1
  cache:
    type: redis
    redis:
      cache-null-values: true
      time-to-live: 100000

auth:
  secret: someSecretCode
  pass-restore: http://localhost:8080/change-password?token=
  email-restore: http://localhost:8080/shift-email?token=

#applicationParams
socialNetwork:
  default:
    page: 0
    size: 5
logging:
  file:
    uploadLogs: false

management:
  endpoints:
    enabled: true
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  endpoint:
    health:
      show-details: always

redis:
  host: localhost


