spring:
  datasource:
    url: jdbc:postgresql://195.133.48.174:5432/social
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none