server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/social
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

auth:
  secret: someSecretCode

#team30BackendParams
team30Backend:
  default:
    page: 0
    size: 20