server:
  port: 8086
  tomcat:
    mbeanregistry:
      enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://195.133.48.174:5432/social
    username: admin
    password: secret
    initialization-mode: never
    data: classpath:/db/changelog/data.sql
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true

#applicationParams
socialNetwork:
  default:
    page: 0
    size: 20
    noteSize: 10
  timezone: Europe/Moscow
  scheduling:
    currencies: 0 1 16 * * MON-FRI
    birthdays: 0 0 8 * * *
    weather: 0 * 7,12,17,22 * * *
  #Банк России
  currency:
    data-path: https://www.cbr-xml-daily.ru/daily_json.js
    units: USD, EUR
  #GisMeteo
  weather:
    data-path: https://api.gismeteo.net/v2/weather/current/
    city-id-path: https://api.gismeteo.net/v2/search/cities/?query=
    token:
      header: X-Gismeteo-Token
      value: 56b30cb255.3443075
  #cities and countries
  geolocation:
    countries-path: https://htmlweb.ru/geo/api.php?location&json&api_key=
    cities-path:
      main: http://htmlweb.ru/geo/api.php?city_name=
      params: "&json&api_key="
    first-countries-in-response: Россия, Беларусь
    first-cities-in-response: Москва (Московская область, Центральный федеральный округ); Санкт-Петербург (Ленинградская область, Санкт-Петербург)
    # 20 запросов в сутки
    token: aae8395d07c1255b0ca5ab1962268afd

auth:
  secret: someSecretCode
  time-to-live: 3600000000
  pass-restore: http://195.133.48.174:8080/change-password?token=
  email-restore: http://195.133.48.174:8080/shift-email?token=

logging:
  file:
    max-history: 1
    path: log
    uploadLogs: true
    uploadTime: 0 0 4 * * *

yandex:
  OAuth: y0_AgAAAABmXrQEAAixEgAAAADUt4an1A5J737iQj-h8tddar39fPxBIgQ

user:
  time-to-delete: 2592000000

spring.mail.protocol: smtps
spring.mail.host: smtp.mail.ru
spring.mail.port: 465
spring.mail.username:  testbd@internet.ru
spring.mail.password: hvYDUwgKj6fkDkFCkgSN
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.ssl.enable: true


management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always
