server:
  port: 8086
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/network
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    data: classpath:/db/changelog/data.sql
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
auth:
  secret: someSecretCode
  time-to-live: 3600000000

#applicationParams
socialNetwork:
  default:
    page: 0
    size: 20
    noteSize: 10

logging:
  file:
    uploadLogs: false




