spring:
  kafka:
    bootstrap-servers: 194.87.244.66:9092
    properties:
      ssl.endpoint.identification.algorithm:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: myGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: soialNetworkApp.kafka.dto

  redis:
    host: localhost
  cache:
    type: redis

  datasource:
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: postgres
    password: test


auth:
  pass-restore: http://localhost:8080/change-password?token=
  email-restore: http://localhost:8080/shift-email?token=

logging:
  file:
    max-history: 1
    path: log
    uploadLogs: false

