spring.datasource.driver-class-name: org.postgresql.Driver


spring.datasource.url: jdbc:postgresql://localhost:5434/postgres?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
spring.datasource.username: postgres
spring.datasource.password: test

spring.jpa.hibernate.ddl-auto: update

spring.jpa.database: postgresql
spring.jpa.open-in-view: true
spring:jpa:database-platform=org:hibernate:dialect: PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: postgres
    password: test
    initialization-mode: always
  jpa:
    hibernate:ddl-auto: validate
    database: postgresql
    open-in-view: true
    database-platform=org:hibernate:dialect: PostgreSQLDialect
    properties:hibernate:jdbc:lob:non_contextual_creation: true
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
  jpa:
    show-sql: true

#applicationParams
socialNetwork:
  default:
    page: 0
    size: 20

server:
  port: 8086
  servlet:
    context-path: "/"


auth:
  secret: someSecretCode
