server:
  port: 8086
#  servlet:
#    context-path: /api/v1
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/network
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:/db/changelog/data.sql
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: create
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
auth:
  secret: someSecretCode

#applicationParams
socialNetwork:
  default:
    page: 0
    size: 20




