spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create




#team30BackendParams
team30Backend:
  default:
    page: 0
    size: 20




