spring:
#  kafka:
#    bootstrap-servers: 194.87.244.66:9092
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/social
    username: postgres
    password: 123
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: dimGroup
  redis:
    port: 6379
    host: localhost
    database: 0
    password: 000000

auth:
  pass-restore: http://localhost:8080/change-password?token=
  email-restore: http://localhost:8080/shift-email?token=

